name: wefarm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  table_calendar: ^3.0.9
  url_launcher: ^6.1.7
  shared_preferences: ^2.2.2
  timeago: ^3.5.0
  http: ^1.3.0
  image_picker: ^0.8.7+3 
  cached_network_image: ^3.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/logo_wefarm.png  # Hapus spasi di nama file!
    - assets/google_logo.png
    - assets/facebook_logo.png
    - assets/Cabai_Rawit.jpg
    - assets/Cabai Merah.jpg
    - assets/

